[package]
name = "rultdb"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
crc32fast = "1.4.2"
lock_api = "0.4.12"
memmap = "0.7.0"
page_size = "0.6.0"
parking_lot = "0.12.3"
thiserror = "1.0.63"
